name: mind
channels:
- defaults
- conda-forge
dependencies:
- cython=0.26=py36_0
- matplotlib=2.0.2=np113py36_0
- numpy=1.13.1=py36_0
- pandas=0.20.3=py36_0
- python=3.6.2
- seaborn=0.8=py36_0
- statsmodels=0.8.0=py36_0

